name = "TypeTheoryUFMG"
version = "0.1.0"
defaultTargets = ["typetheoryufmg"]

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "TypeTheoryUFMG"

[[lean_exe]]
name = "typetheoryufmg"
root = "Main"
